[tool.poetry]
name = "testing_releases"
version = "0.0.1"
description = "Just a test repo for me to test releases on."
authors = ["Bilbottom"]
readme = "README.md"
packages = [{include = "src"}]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.test.dependencies]
pre-commit = "^3.0.0"
pytest = "^7.0.0"
pytest-cov = "^3.0.0"

[tool.pytest.ini_options]
addopts = "--cov=src"
testpaths = [
    "tests",
]

[tool.isort]
profile = "black"
