[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "testing_releases"
version = "0.1.1"
description = "Just a test repo for me to test releases on."
authors = ["Bilbottom"]
readme = "README.md"
packages = [{include = "testing_releases"}]

[tool.poetry.scripts]
testing-releases = 'testing_releases:main'

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.test.dependencies]
pre-commit = "^3.0.0"
pytest = "^7.0.0"
pytest-cov = "^4.0.0"


[tool.pytest.ini_options]
addopts = "--cov=src"
testpaths = [
    "tests",
]


[tool.isort]
profile = "black"


[tool.semantic_release]
#version_variables = ["pyproject.toml:tool.poetry.version"]
version_toml = ["pyproject.toml:tool.poetry.version"]

[tool.semantic_release.branches.main]
match = "main"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release.commit_parser_options]
allowed_tags = [
    "build",
    "chore",
#    "ci",
    "docs",
    "feat",
    "fix",
    "perf",
    "refactor",
    "style",
    "test",
]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
